# Generated by Django 3.2 on 2022-10-20 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalActivityLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activity_level_before_pain', models.CharField(blank=True, max_length=256, null=True)),
                ('activity_level_during_pain', models.CharField(blank=True, max_length=256, null=True)),
                ('regular_activity', models.CharField(blank=True, max_length=256, null=True)),
                ('activity_per_week', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCharacteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=256, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=256, null=True)),
                ('body_type', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Personal Characteristics',
                'verbose_name_plural': 'Personal Characteristics',
            },
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chronic_back_pain', models.BooleanField(blank=True, null=True)),
                ('unsteady_gait', models.BooleanField(blank=True, null=True)),
                ('bowel_bladder_symptoms', models.BooleanField(blank=True, null=True)),
                ('relief_with_rest', models.BooleanField(blank=True, null=True)),
                ('leg_pain', models.BooleanField(blank=True, null=True)),
                ('leukaemia', models.BooleanField(blank=True, null=True)),
                ('chemotherapy', models.BooleanField(blank=True, null=True)),
                ('gastrointestinal_carcinoma', models.BooleanField(blank=True, null=True)),
                ('surgery', models.BooleanField(blank=True, null=True)),
                ('myositis', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('SEMG', 'SEMG'), ('INERTIAL', 'INERTIAL'), ('IR', 'IR')], default=None, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionLevel2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pain_since', models.CharField(blank=True, max_length=256, null=True)),
                ('pain_location', models.CharField(blank=True, max_length=256, null=True)),
                ('constant_pain', models.CharField(blank=True, max_length=256, null=True)),
                ('pain_start', models.CharField(blank=True, max_length=256, null=True)),
                ('relation_physical_activity', models.CharField(blank=True, max_length=256, null=True)),
                ('relation_rest', models.CharField(blank=True, max_length=256, null=True)),
                ('is_pain_spreading', models.CharField(blank=True, max_length=256, null=True)),
                ('pain_description', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackPainLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('back_pain_level', models.IntegerField(blank=True, null=True)),
                ('is_job_heavy', models.BooleanField(blank=True, null=True)),
                ('is_desk_work_all_day', models.BooleanField(blank=True, null=True)),
                ('healthcare_consult', models.BooleanField(blank=True, null=True)),
                ('pain_relief', models.CharField(blank=True, max_length=256, null=True)),
                ('is_taking_medication', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
