# Generated by Django 3.2 on 2022-09-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalcharacteristics',
            options={'verbose_name': 'Personal Characteristics', 'verbose_name_plural': 'Personal Characteristics'},
        ),
    ]
