# Generated by Django 3.2 on 2023-02-21 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20221027_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcharacteristics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pc', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
