# Generated by Django 3.2 on 2022-12-24 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20221027_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericInertialSensorsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l5s1_lateral', models.FloatField(blank=True, null=True)),
                ('l5s1_axial', models.FloatField(blank=True, null=True)),
                ('l5s1_flexion', models.FloatField(blank=True, null=True)),
                ('l4l3_lateral', models.FloatField(blank=True, null=True)),
                ('l4l3_axial', models.FloatField(blank=True, null=True)),
                ('l4l3_flexion', models.FloatField(blank=True, null=True)),
                ('l1t12_lateral', models.FloatField(blank=True, null=True)),
                ('l1t12_axial', models.FloatField(blank=True, null=True)),
                ('l1t12_flexion', models.FloatField(blank=True, null=True)),
                ('t9t8_lateral', models.FloatField(blank=True, null=True)),
                ('t9t8_axial', models.FloatField(blank=True, null=True)),
                ('t9t8_flexion', models.FloatField(blank=True, null=True)),
                ('t1c7_lateral', models.FloatField(blank=True, null=True)),
                ('t1c7_axial', models.FloatField(blank=True, null=True)),
                ('t1c7_flexion', models.FloatField(blank=True, null=True)),
                ('c1head_lateral', models.FloatField(blank=True, null=True)),
                ('c1head_axial', models.FloatField(blank=True, null=True)),
                ('c1head_flexion', models.FloatField(blank=True, null=True)),
                ('com_posx', models.FloatField(blank=True, null=True)),
                ('com_posy', models.FloatField(blank=True, null=True)),
                ('com_posz', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericSEMGSensorsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('leftc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('right_multifidus', models.FloatField(blank=True, null=True)),
                ('left_multifidus', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_steps', to='infra.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('COMPLETED', 'Completed'), ('STARTED', 'Started'), ('FAILED', 'Failed')], default='CREATED', max_length=256)),
                ('type', models.CharField(choices=[('CALIBRATION', 'Calibration'), ('TREATMENT', 'Treatment')], default='CALIBRATION', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentGoldStandardInertialData',
            fields=[
                ('genericinertialsensorsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='infra.genericinertialsensorsdata')),
                ('data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            bases=('infra.genericinertialsensorsdata',),
        ),
        migrations.CreateModel(
            name='TreatmentGoldStandardSEMGData',
            fields=[
                ('genericsemgsensorsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='infra.genericsemgsensorsdata')),
                ('data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            bases=('infra.genericsemgsensorsdata',),
        ),
        migrations.CreateModel(
            name='SessionTreatmentIPCReceived',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('semg_received', models.BooleanField()),
                ('semg_received_time', models.DateTimeField(auto_now_add=True)),
                ('inertial_received', models.BooleanField()),
                ('inertial_received_time', models.DateTimeField(auto_now_add=True)),
                ('ir_received', models.BooleanField()),
                ('ir_received_time', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.BooleanField(default=False)),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.session')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStepOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(max_length=2)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
            ],
        ),
        migrations.CreateModel(
            name='IRSensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('thermal', models.FloatField(blank=True, null=True)),
                ('read_status', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.devices')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.session', verbose_name='Session')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.session')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
            ],
        ),
        migrations.CreateModel(
            name='UserGoldStandardSEMGData',
            fields=[
                ('genericsemgsensorsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='infra.genericsemgsensorsdata')),
                ('data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_final_data', models.BooleanField(default=False)),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedure')),
                ('procedure_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('infra.genericsemgsensorsdata',),
        ),
        migrations.CreateModel(
            name='UserGoldStandardInertialData',
            fields=[
                ('genericinertialsensorsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='infra.genericinertialsensorsdata')),
                ('data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_final_data', models.BooleanField(default=False)),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedure')),
                ('procedure_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('infra.genericinertialsensorsdata',),
        ),
        migrations.CreateModel(
            name='ProcedureGoldStandardSEMGData',
            fields=[
                ('genericsemgsensorsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='infra.genericsemgsensorsdata')),
                ('data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_final_data', models.BooleanField(default=False)),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedure')),
                ('procedure_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
            ],
            bases=('infra.genericsemgsensorsdata',),
        ),
        migrations.CreateModel(
            name='ProcedureGoldStandardInertialData',
            fields=[
                ('genericinertialsensorsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='infra.genericinertialsensorsdata')),
                ('data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_final_data', models.BooleanField(default=False)),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedure')),
                ('procedure_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
            ],
            bases=('infra.genericinertialsensorsdata',),
        ),
        migrations.CreateModel(
            name='CalibrationStepSEMGData',
            fields=[
                ('genericsemgsensorsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='infra.genericsemgsensorsdata')),
                ('data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('read_status', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.devices')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.session', verbose_name='Session')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.calibrationstep')),
            ],
            bases=('infra.genericsemgsensorsdata',),
        ),
        migrations.CreateModel(
            name='CalibrationStepIRData',
            fields=[
                ('irsensordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infra.irsensordata')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.calibrationstep')),
            ],
            bases=('infra.irsensordata',),
        ),
        migrations.CreateModel(
            name='CalibrationStepInertialData',
            fields=[
                ('genericinertialsensorsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='infra.genericinertialsensorsdata')),
                ('data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('read_status', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.devices')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.session', verbose_name='Session')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.calibrationstep')),
            ],
            bases=('infra.genericinertialsensorsdata',),
        ),
        migrations.AddConstraint(
            model_name='calibrationstep',
            constraint=models.UniqueConstraint(fields=('session', 'step'), name='Single-Calibration-with-a-step-constraint'),
        ),
    ]
