# Generated by Django 3.2 on 2023-01-26 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceduregoldstandardinertialdata',
            name='procedure_step',
        ),
    ]
