# Generated by Django 3.2 on 2022-12-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoldstandardinertialdata',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='usergoldstandardinertialdata',
            name='procedure_step',
        ),
        migrations.RemoveField(
            model_name='usergoldstandardsemgdata',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='usergoldstandardsemgdata',
            name='procedure_step',
        ),
        migrations.AddField(
            model_name='treatmentgoldstandardinertialdata',
            name='is_final_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentgoldstandardsemgdata',
            name='is_final_data',
            field=models.BooleanField(default=False),
        ),
    ]
