# Generated by Django 3.2 on 2022-11-01 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221027_2235'),
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inertialsensordata',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.devices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irsensordata',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.devices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semgsensordata',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.devices'),
            preserve_default=False,
        ),
    ]
