# Generated by Django 3.2 on 2023-01-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_remove_proceduregoldstandardinertialdata_procedure_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceduregoldstandardsemgdata',
            name='procedure_step',
        ),
    ]
