# Generated by Django 3.2 on 2022-11-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20221101_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='irsensordata',
            name='thermal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
