# Generated by Django 3.2 on 2022-11-03 17:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_irsensordata_thermal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_steps', to='infra.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStepOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(max_length=2)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.session')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
            ],
        ),
        migrations.AddConstraint(
            model_name='calibrationstep',
            constraint=models.UniqueConstraint(fields=('session', 'step'), name='Single-Calibration-with-a-step-constraint'),
        ),
    ]
