# Generated by Django 3.2 on 2023-01-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_remove_proceduregoldstandardsemgdata_procedure_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationstepirdata',
            name='device',
        ),
    ]
