# Generated by Django 3.2 on 2022-11-05 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_auto_20221103_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTreatmentIPCReceived',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('semg_received', models.BooleanField()),
                ('semg_received_time', models.DateTimeField(auto_now_add=True)),
                ('inertial_received', models.BooleanField()),
                ('inertial_received_time', models.DateTimeField(auto_now_add=True)),
                ('ir_received', models.BooleanField()),
                ('ir_received_time', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.BooleanField(default=False)),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.session')),
            ],
        ),
    ]
