# Generated by Django 3.2 on 2023-03-01 20:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_remove_calibrationstepirdata_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontreatmentipcreceived',
            name='inertial_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessiontreatmentipcreceived',
            name='ir_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessiontreatmentipcreceived',
            name='semg_received',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TreatmentIRData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('thermal', models.FloatField(blank=True, null=True)),
                ('read_status', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.session', verbose_name='Session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
