# Generated by Django 3.2 on 2022-11-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_sessiontreatmentipcreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='inertialsensordata',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irsensordata',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semgsensordata',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
