# Generated by Django 3.2 on 2023-03-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_auto_20230301_2036'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calibrationstep',
            name='Single-Calibration-with-a-step-constraint',
        ),
    ]
