# Generated by Django 3.2 on 2022-11-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0006_auto_20221105_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationStepSEMGData',
            fields=[
                ('semgsensordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infra.semgsensordata')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.calibrationstep')),
            ],
            bases=('infra.semgsensordata',),
        ),
        migrations.CreateModel(
            name='CalibrationStepIRData',
            fields=[
                ('irsensordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infra.irsensordata')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.calibrationstep')),
            ],
            bases=('infra.irsensordata',),
        ),
        migrations.CreateModel(
            name='CalibrationStepInertialData',
            fields=[
                ('inertialsensordata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infra.inertialsensordata')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.calibrationstep')),
            ],
            bases=('infra.inertialsensordata',),
        ),
    ]
