# Generated by Django 3.2 on 2023-05-18 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0006_remove_calibrationstep_single-calibration-with-a-step-constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontreatmentipcreceived',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
