# Generated by Django 3.2 on 2022-11-06 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infra', '0007_calibrationstepinertialdata_calibrationstepirdata_calibrationstepsemgdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoldStandardSEMGData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rightc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('leftc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('right_multifidus', models.FloatField(blank=True, null=True)),
                ('left_multifidus', models.FloatField(blank=True, null=True)),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedure')),
                ('procedure_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoldStandardInertialData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('l5s1_lateral', models.FloatField(blank=True, null=True)),
                ('l5s1_axial', models.FloatField(blank=True, null=True)),
                ('l5s1_flexion', models.FloatField(blank=True, null=True)),
                ('l4l3_lateral', models.FloatField(blank=True, null=True)),
                ('l4l3_axial', models.FloatField(blank=True, null=True)),
                ('l4l3_flexion', models.FloatField(blank=True, null=True)),
                ('l1t12_lateral', models.FloatField(blank=True, null=True)),
                ('l1t12_axial', models.FloatField(blank=True, null=True)),
                ('l1t12_flexion', models.FloatField(blank=True, null=True)),
                ('t9t8_lateral', models.FloatField(blank=True, null=True)),
                ('t9t8_axial', models.FloatField(blank=True, null=True)),
                ('t9t8_flexion', models.FloatField(blank=True, null=True)),
                ('t1c7_lateral', models.FloatField(blank=True, null=True)),
                ('t1c7_axial', models.FloatField(blank=True, null=True)),
                ('t1c7_flexion', models.FloatField(blank=True, null=True)),
                ('c1head_lateral', models.FloatField(blank=True, null=True)),
                ('c1head_axial', models.FloatField(blank=True, null=True)),
                ('c1head_flexion', models.FloatField(blank=True, null=True)),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedure')),
                ('procedure_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureGoldStandardSEMGData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rightc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('leftc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('right_multifidus', models.FloatField(blank=True, null=True)),
                ('left_multifidus', models.FloatField(blank=True, null=True)),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedure')),
                ('procedure_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureGoldStandardInertialData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('l5s1_lateral', models.FloatField(blank=True, null=True)),
                ('l5s1_axial', models.FloatField(blank=True, null=True)),
                ('l5s1_flexion', models.FloatField(blank=True, null=True)),
                ('l4l3_lateral', models.FloatField(blank=True, null=True)),
                ('l4l3_axial', models.FloatField(blank=True, null=True)),
                ('l4l3_flexion', models.FloatField(blank=True, null=True)),
                ('l1t12_lateral', models.FloatField(blank=True, null=True)),
                ('l1t12_axial', models.FloatField(blank=True, null=True)),
                ('l1t12_flexion', models.FloatField(blank=True, null=True)),
                ('t9t8_lateral', models.FloatField(blank=True, null=True)),
                ('t9t8_axial', models.FloatField(blank=True, null=True)),
                ('t9t8_flexion', models.FloatField(blank=True, null=True)),
                ('t1c7_lateral', models.FloatField(blank=True, null=True)),
                ('t1c7_axial', models.FloatField(blank=True, null=True)),
                ('t1c7_flexion', models.FloatField(blank=True, null=True)),
                ('c1head_lateral', models.FloatField(blank=True, null=True)),
                ('c1head_axial', models.FloatField(blank=True, null=True)),
                ('c1head_flexion', models.FloatField(blank=True, null=True)),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedure')),
                ('procedure_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infra.procedurestep')),
            ],
        ),
    ]
