# Generated by Django 3.2 on 2023-07-11 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0007_sessiontreatmentipcreceived_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationAndTreatmentSessionRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calibration_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_link_session', to='infra.session')),
                ('treatment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_link_session', to='infra.session')),
            ],
        ),
    ]
