# Generated by Django 3.2 on 2022-10-20 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('COMPLETED', 'Completed'), ('STARTED', 'Started'), ('FAILED', 'Failed')], default='CREATED', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenericInertialSensors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('l5s1_lateral', models.FloatField(blank=True, null=True)),
                ('l5s1_axial', models.FloatField(blank=True, null=True)),
                ('l5s1_flexion', models.FloatField(blank=True, null=True)),
                ('l4l3_lateral', models.FloatField(blank=True, null=True)),
                ('l4l3_axial', models.FloatField(blank=True, null=True)),
                ('l4l3_flexion', models.FloatField(blank=True, null=True)),
                ('l1t12_lateral', models.FloatField(blank=True, null=True)),
                ('l1t12_axial', models.FloatField(blank=True, null=True)),
                ('l1t12_flexion', models.FloatField(blank=True, null=True)),
                ('t9t8_lateral', models.FloatField(blank=True, null=True)),
                ('t9t8_axial', models.FloatField(blank=True, null=True)),
                ('t9t8_flexion', models.FloatField(blank=True, null=True)),
                ('t1c7_lateral', models.FloatField(blank=True, null=True)),
                ('t1c7_axial', models.FloatField(blank=True, null=True)),
                ('t1c7_flexion', models.FloatField(blank=True, null=True)),
                ('c1head_lateral', models.FloatField(blank=True, null=True)),
                ('c1head_axial', models.FloatField(blank=True, null=True)),
                ('c1head_flexion', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericSEMGSensors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rightc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('leftc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('right_multifidus', models.FloatField(blank=True, null=True)),
                ('left_multifidus', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_steps', to='calibration.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationInertialSensors',
            fields=[
                ('genericinertialsensors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calibration.genericinertialsensors')),
            ],
            bases=('calibration.genericinertialsensors',),
        ),
        migrations.CreateModel(
            name='CalibrationSEMGSensors',
            fields=[
                ('genericsemgsensors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calibration.genericsemgsensors')),
            ],
            bases=('calibration.genericsemgsensors',),
        ),
        migrations.CreateModel(
            name='ProcedureStepOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(max_length=2)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibration')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep')),
            ],
        ),
        migrations.CreateModel(
            name='GoldStandardSEMGSensors',
            fields=[
                ('genericsemgsensors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calibration.genericsemgsensors')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep')),
            ],
            bases=('calibration.genericsemgsensors',),
        ),
        migrations.CreateModel(
            name='GoldStandardInertialSensors',
            fields=[
                ('genericinertialsensors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calibration.genericinertialsensors')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep')),
            ],
            bases=('calibration.genericinertialsensors',),
        ),
        migrations.AddConstraint(
            model_name='calibrationstep',
            constraint=models.UniqueConstraint(fields=('session', 'step'), name='Single-Calibration-with-a-step-constraint'),
        ),
        migrations.AddField(
            model_name='calibrationsemgsensors',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibration'),
        ),
        migrations.AddField(
            model_name='calibrationsemgsensors',
            name='step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep'),
        ),
        migrations.AddField(
            model_name='calibrationinertialsensors',
            name='step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep'),
        ),
    ]
