# Generated by Django 3.2 on 2022-09-24 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldStandardInertialSensors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('l5s1_lateral', models.FloatField(blank=True, null=True)),
                ('l5s1_axial', models.FloatField(blank=True, null=True)),
                ('l5s1_flexion', models.FloatField(blank=True, null=True)),
                ('l4l3_lateral', models.FloatField(blank=True, null=True)),
                ('l4l3_axial', models.FloatField(blank=True, null=True)),
                ('l4l3_flexion', models.FloatField(blank=True, null=True)),
                ('l1t12_lateral', models.FloatField(blank=True, null=True)),
                ('l1t12_axial', models.FloatField(blank=True, null=True)),
                ('l1t12_flexion', models.FloatField(blank=True, null=True)),
                ('t9t8_lateral', models.FloatField(blank=True, null=True)),
                ('t9t8_axial', models.FloatField(blank=True, null=True)),
                ('t9t8_flexion', models.FloatField(blank=True, null=True)),
                ('t1c7_lateral', models.FloatField(blank=True, null=True)),
                ('t1c7_axial', models.FloatField(blank=True, null=True)),
                ('t1c7_flexion', models.FloatField(blank=True, null=True)),
                ('c1head_lateral', models.FloatField(blank=True, null=True)),
                ('c1head_axial', models.FloatField(blank=True, null=True)),
                ('c1head_flexion', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldStandardSEMGSensors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rightc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('leftc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('right_multifidus', models.FloatField(blank=True, null=True)),
                ('left_multifidus', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
