# Generated by Django 3.2 on 2022-09-24 02:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_steps', to='calibration.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStepOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(max_length=2)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep')),
            ],
        ),
        migrations.AddField(
            model_name='goldstandardinertialsensors',
            name='step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep'),
        ),
        migrations.AddField(
            model_name='goldstandardsemgsensors',
            name='step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep'),
        ),
    ]
