# Generated by Django 3.2 on 2022-11-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationsemgsensors',
            name='genericsemgsensors_ptr',
        ),
        migrations.RemoveField(
            model_name='calibrationsemgsensors',
            name='session',
        ),
        migrations.RemoveField(
            model_name='calibrationsemgsensors',
            name='step',
        ),
        migrations.RemoveField(
            model_name='calibrationstep',
            name='session',
        ),
        migrations.RemoveField(
            model_name='calibrationstep',
            name='step',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='genericinertialsensors_ptr',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='step',
        ),
        migrations.RemoveField(
            model_name='goldstandardsemgsensors',
            name='genericsemgsensors_ptr',
        ),
        migrations.RemoveField(
            model_name='goldstandardsemgsensors',
            name='step',
        ),
        migrations.RemoveField(
            model_name='procedurestep',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='proceduresteporder',
            name='step',
        ),
        migrations.DeleteModel(
            name='CalibrationInertialSensors',
        ),
        migrations.DeleteModel(
            name='CalibrationSEMGSensors',
        ),
        migrations.DeleteModel(
            name='CalibrationStep',
        ),
        migrations.DeleteModel(
            name='GenericInertialSensors',
        ),
        migrations.DeleteModel(
            name='GenericSEMGSensors',
        ),
        migrations.DeleteModel(
            name='GoldStandardInertialSensors',
        ),
        migrations.DeleteModel(
            name='GoldStandardSEMGSensors',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='ProcedureStep',
        ),
        migrations.DeleteModel(
            name='ProcedureStepOrder',
        ),
    ]
