# Generated by Django 3.2 on 2022-09-24 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calibration', '0002_auto_20220924_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericInertialSensors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('l5s1_lateral', models.FloatField(blank=True, null=True)),
                ('l5s1_axial', models.FloatField(blank=True, null=True)),
                ('l5s1_flexion', models.FloatField(blank=True, null=True)),
                ('l4l3_lateral', models.FloatField(blank=True, null=True)),
                ('l4l3_axial', models.FloatField(blank=True, null=True)),
                ('l4l3_flexion', models.FloatField(blank=True, null=True)),
                ('l1t12_lateral', models.FloatField(blank=True, null=True)),
                ('l1t12_axial', models.FloatField(blank=True, null=True)),
                ('l1t12_flexion', models.FloatField(blank=True, null=True)),
                ('t9t8_lateral', models.FloatField(blank=True, null=True)),
                ('t9t8_axial', models.FloatField(blank=True, null=True)),
                ('t9t8_flexion', models.FloatField(blank=True, null=True)),
                ('t1c7_lateral', models.FloatField(blank=True, null=True)),
                ('t1c7_axial', models.FloatField(blank=True, null=True)),
                ('t1c7_flexion', models.FloatField(blank=True, null=True)),
                ('c1head_lateral', models.FloatField(blank=True, null=True)),
                ('c1head_axial', models.FloatField(blank=True, null=True)),
                ('c1head_flexion', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericSEMGSensors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rightc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('leftc4_paraspinal', models.FloatField(blank=True, null=True)),
                ('right_multifidus', models.FloatField(blank=True, null=True)),
                ('left_multifidus', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='c1head_axial',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='c1head_flexion',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='c1head_lateral',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='l1t12_axial',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='l1t12_flexion',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='l1t12_lateral',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='l4l3_axial',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='l4l3_flexion',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='l4l3_lateral',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='l5s1_axial',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='l5s1_flexion',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='l5s1_lateral',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='t1c7_axial',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='t1c7_flexion',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='t1c7_lateral',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='t9t8_axial',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='t9t8_flexion',
        ),
        migrations.RemoveField(
            model_name='goldstandardinertialsensors',
            name='t9t8_lateral',
        ),
        migrations.RemoveField(
            model_name='goldstandardsemgsensors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goldstandardsemgsensors',
            name='left_multifidus',
        ),
        migrations.RemoveField(
            model_name='goldstandardsemgsensors',
            name='leftc4_paraspinal',
        ),
        migrations.RemoveField(
            model_name='goldstandardsemgsensors',
            name='right_multifidus',
        ),
        migrations.RemoveField(
            model_name='goldstandardsemgsensors',
            name='rightc4_paraspinal',
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='goldstandardinertialsensors',
            name='genericinertialsensors_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calibration.genericinertialsensors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goldstandardsemgsensors',
            name='genericsemgsensors_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calibration.genericsemgsensors'),
            preserve_default=False,
        ),
    ]
