# Generated by Django 3.2 on 2022-09-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_auto_20220924_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationInertialSensors',
            fields=[
                ('genericinertialsensors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calibration.genericinertialsensors')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep')),
            ],
            bases=('calibration.genericinertialsensors',),
        ),
    ]
