# Generated by Django 3.2 on 2022-09-24 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_calibrationinertialsensors'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSEMGSensors',
            fields=[
                ('genericsemgsensors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calibration.genericsemgsensors')),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep')),
            ],
            bases=('calibration.genericsemgsensors',),
        ),
    ]
