# Generated by Django 3.2 on 2022-09-24 04:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_alter_calibration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.procedurestep')),
            ],
        ),
    ]
