# Generated by Django 3.2 on 2022-09-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0009_calibration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationstep',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibration'),
        ),
    ]
