# Generated by Django 3.2 on 2022-09-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0010_calibrationstep_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('COMPLETED', 'Completed'), ('STARTED', 'Started'), ('FAILED', 'Failed')], default='CREATED', max_length=256),
        ),
    ]
