# Generated by Django 3.2 on 2022-09-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0011_alter_calibration_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calibrationstep',
            constraint=models.UniqueConstraint(fields=('session', 'step'), name='Single-Calibration-with-a-step-constraint'),
        ),
    ]
